routes:
  /:
    controller: channel
    template: index
    # filter: 
    # rss: true
    

  /recommended/:
    # controller: channel
    # filter: tag:recommended
    template: recommended
    rss: false
    

collections:
  # /:
  #   template: home

  /es/:
    template: index-es
    permalink: /es/{slug}/
    filter: tag:es+tag:-en+tag:-br
    # order: published_at.asc
    data: tag.es
    # rss: true

  /en/:
    template: index-en
    permalink: /en/{slug}/
    filter: tag:en+tag:-es+tag:-br
    # order: published_at/.asc
    data: tag.en
    # rss: true

  /br/:
    template: index-br
    permalink: /br/{slug}/
    filter: tag:br+tag:-es+tag:-en
    # order: published_at.asc
    data: tag.br
    # rss: true


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/




